ExampleClusterOnly03:
  region: ${region}
  rollbackOnFailure: true
  validationFailureLevel: WARNING
  suppressValidators:
    - type:KeyPairValidator
  configuration: files/cluster-config.yaml
ExampleClusterOnly04:
  region: ${region}
  rollbackOnFailure: false
  configuration: files/cluster-config.yaml
