exampleCluster1:
  region: ${region} 
  rollbackOnFailure: true 
  validationFailureLevel: WARNING
  configuration: files/cluster-config.yaml
exampleCluster2:
  region: ${region} 
  rollbackOnFailure: false
  configuration: files/cluster-config.yaml
