ExampleClusterOnly03:
  region: ${region}
  rollbackOnFailure: true
  validationFailureLevel: WARNING
  configuration: files/cluster-config.yaml
ExampleClusterOnly04:
  region: ${region}
  rollbackOnFailure: false
  configuration: files/cluster-config.yaml
